### ISSUE TITLE
fmri_roi_extraction mask file not found

### ISSUE THREAD

**Issue by ToniKaiser** [cohenlabUNC/clpipe#129]
Hi,

I have a question about the fmri_roi_extraction function. When I try to run it, it can't find the brain mask produced by fmriprep because it is searching for the wrong name. 
Is there a possibility to change that name? 
<img width="891" alt="2020-11-18_14h58_38" src="https://user-images.githubusercontent.com/74664289/99539500-9a050280-29ae-11eb-94b0-50d19d9c840a.png">

Thanks a lot for your help!
Best,
Antonia
----------------------------------------
UPDATE:
I found a work-around by renaming the brain mask files in the fmriprep-directory (deleting "space-MNI152NLin2009cAsym_").

**Comment by trh3** [comment]
Hello! Apologies for the delayed response! Glad you found that workaround. I suspect the original cause of the issue was because your ['ROIExtractionOptions']['TargetSuffix'] field looked like "space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz"? I will update to allow for a bit more control over that mask syntax, because it wouldn't work well if there are multiple outcome spaces.

**Comment by ToniKaiser** [comment]
Hi,
The  ['ROIExtractionOptions']['TargetSuffix'] field is "preproc_bold_postproc.nii.gz" for the file coming out of fmri_postprocess. But the ['PostProcessingOptions']['TargetSuffix'] is indeed "space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz". Let me know if you have time to include the new syntax soon, I haven't run the entire dataset yet and would be very happy to update first! Otherwise, I'll proceed with my workaround, which also does the trick.
Thanks so much for your efforts!
